export const DEFAULT_PROMPTS = [
  // Original 50
  "Take a photo of something blue",
  "Take a photo of something moving",
  "Something that casts a long shadow",
  "A texture that looks like a map",
  "Something older than you",
  "A repetitive pattern",
  "Light hitting a surface in an interesting way",
  "Something perfectly symmetrical",
  "A reflection in an unexpected place",
  "Something that represents 'speed'",
  "Two things that don't belong together",
  "Extreme close-up of an everyday object",
  "Something that makes you feel calm",
  "A splash of bright color in a dull area",
  "Something that looks like a face (pareidolia)",
  "The view from a very low angle",
  "Something that shows the passage of time",
  "A silhouette against the sky",
  "Something that fits perfectly inside something else",
  "An object that has a story to tell",
  "Something tiny that usually goes unnoticed",
  "A leading line that draws the eye",
  "Something that looks like a different material than it is",
  "A frame within a frame",
  "Something that represents a sound",
  "An interesting shadow of a boring object",
  "Something that evokes a specific memory",
  "A pop of nature in a city environment",
  "Something that is usually hidden",
  "The color of your current mood",
  "Something that starts with the letter 'S'",
  "A sharp contrast between light and dark",
  "Something that is fragile",
  "A collection of similar things",
  "Something that reminds you of a movie",
  "An abstract shape in the wild",
  "Something that has been repaired",
  "A splash of water or a liquid in motion",
  "Something that represents 'home'",
  "An object that is out of place",
  "Something that is perfectly round",
  "A sign with a message that fits your day",
  "Something that has a unique texture",
  "An interesting geometric shape",
  "Something that represents 'morning'",
  "The oldest thing in the room",
  "Something that makes a shadow bigger than itself",
  "A detail of a piece of clothing",
  "Something that is half-hidden",
  "A combination of three different colors",
  // 300 new prompts
  "Something that feels warm to the touch",
  "A pattern created by nature",
  "Something you use every day but never photograph",
  "A curve that catches your eye",
  "Something that glows",
  "A surface covered in dust",
  "Something that looks like it's watching you",
  "The boundary between two different areas",
  "Something that represents 'freedom'",
  "An object that's been worn down by use",
  "Something that's the color of the sky at sunset",
  "A shadow that looks like something else",
  "Something transparent or translucent",
  "A texture that would feel rough",
  "Something that makes you smile",
  "A straight line in a curved world",
  "Something that looks like it belongs in a museum",
  "The contrast between old and new",
  "Something that represents 'silence'",
  "A pattern made by people",
  "Something that looks different from far away",
  "An object casting multiple shadows",
  "Something that's the same color as your shoes",
  "A surface with water droplets",
  "Something that represents 'growth'",
  "An interesting crack or split",
  "Something that looks like a painting",
  "A corner where two walls meet",
  "Something that represents 'chaos'",
  "A smooth surface in a rough environment",
  "Something that catches the light",
  "A pattern in the pavement",
  "Something that looks like it's melting",
  "An object that's surprisingly colorful",
  "Something that represents 'strength'",
  "A texture you'd want to touch",
  "Something that looks like it's floating",
  "The edge of a shadow",
  "Something that represents 'peace'",
  "An object with an interesting smell",
  "Something that looks like it's upside down",
  "A surface with interesting marks",
  "Something that represents 'energy'",
  "An object that's been abandoned",
  "Something that looks like a letter of the alphabet",
  "A pattern created by light",
  "Something that represents 'loneliness'",
  "An object that's surprisingly heavy-looking",
  "Something that looks like it's about to fall",
  "A surface that's perfectly flat",
  "Something that represents 'joy'",
  "An object with an interesting sound",
  "Something that looks like it's been painted",
  "A pattern made by wind",
  "Something that represents 'mystery'",
  "An object that's covered in stickers",
  "Something that looks like a number",
  "A surface with interesting reflections",
  "Something that represents 'hope'",
  "An object that's partially hidden",
  "Something that looks like it's breathing",
  "A pattern made by footsteps",
  "Something that represents 'danger'",
  "An object that's been forgotten",
  "Something that looks like a word",
  "A surface with interesting grooves",
  "Something that represents 'comfort'",
  "An object that's surprisingly light",
  "Something that looks like it's spinning",
  "A pattern created by shadows",
  "Something that represents 'surprise'",
  "An object that's been decorated",
  "Something that looks like a shape from geometry",
  "A surface with an interesting temperature",
  "Something that represents 'wonder'",
  "An object that's been weathered",
  "Something that looks like it's frozen in time",
  "A pattern made by dripping",
  "Something that represents 'balance'",
  "An object that's been repurposed",
  "Something that looks like a natural formation",
  "A surface with an interesting sheen",
  "Something that represents 'change'",
  "An object that's been left behind",
  "Something that looks like it's dancing",
  "A pattern made by peeling",
  "Something that represents 'stillness'",
  "An object that's been modified",
  "Something that looks like an optical illusion",
  "A surface with interesting bumps",
  "Something that represents 'flow'",
  "An object that's been polished",
  "Something that looks like it's glowing from within",
  "A pattern made by scratching",
  "Something that represents 'resistance'",
  "An object that's been torn",
  "Something that looks like it's alive",
  "A surface with an interesting grain",
  "Something that represents 'harmony'",
  "An object that's been stacked",
  "Something that looks like it's falling",
  "A pattern made by rubbing",
  "Something that represents 'tension'",
  "An object that's been folded",
  "Something that looks like a symbol",
  "A surface with interesting pores",
  "Something that represents 'release'",
  "An object that's been twisted",
  "Something that looks like it's rising",
  "A pattern made by pressing",
  "Something that represents 'depth'",
  "An object that's been layered",
  "Something that looks like it's expanding",
  "A surface with interesting ridges",
  "Something that represents 'movement'",
  "An object that's been compressed",
  "Something that looks like it's contracting",
  "A pattern made by dragging",
  "Something that represents 'weight'",
  "An object that's been suspended",
  "Something that looks like it's sinking",
  "A surface with interesting scales",
  "Something that represents 'flight'",
  "An object that's been anchored",
  "Something that looks like it's drifting",
  "A pattern made by swirling",
  "Something that represents 'grounding'",
  "An object that's been elevated",
  "Something that looks like it's tumbling",
  "A surface with interesting waves",
  "Something that represents 'stability'",
  "An object that's been tilted",
  "Something that looks like it's sliding",
  "A pattern made by rippling",
  "Something that represents 'turbulence'",
  "An object that's been propped up",
  "Something that looks like it's rolling",
  "A surface with interesting folds",
  "Something that represents 'calm'",
  "An object that's been balanced",
  "Something that looks like it's bouncing",
  "A pattern made by splashing",
  "Something that represents 'stillness after motion'",
  "An object that's been caught mid-air",
  "Something that looks like it's spinning to a stop",
  "A surface with interesting ripples",
  "Something that represents 'anticipation'",
  "An object that's been paused",
  "Something that looks like it's about to start",
  "A pattern made by settling",
  "Something that represents 'completion'",
  "An object that's been finished",
  "Something that looks like it's been waiting",
  "A surface with interesting settling patterns",
  "Something that represents 'beginning'",
  "An object that's been started",
  "Something that looks like it's just arrived",
  "A pattern made by emerging",
  "Something that represents 'transformation'",
  "An object that's been changed",
  "Something that looks like it's becoming something else",
  "A surface with interesting oxidation",
  "Something that represents 'preservation'",
  "An object that's been protected",
  "Something that looks like it's been kept safe",
  "A pattern made by aging",
  "Something that represents 'renewal'",
  "An object that's been refreshed",
  "Something that looks like it's been restored",
  "A surface with interesting patina",
  "Something that represents 'decay'",
  "An object that's been crumbling",
  "Something that looks like it's falling apart",
  "A pattern made by erosion",
  "Something that represents 'endurance'",
  "An object that's been surviving",
  "Something that looks like it's been through a lot",
  "A surface with interesting wear",
  "Something that represents 'fragility'",
  "An object that's been cracked",
  "Something that looks like it could break",
  "A pattern made by breaking",
  "Something that represents 'wholeness'",
  "An object that's been complete",
  "Something that looks like it's never been touched",
  "A surface with interesting pristine areas",
  "Something that represents 'imperfection'",
  "An object that's been damaged",
  "Something that looks like it has a flaw",
  "A pattern made by irregularity",
  "Something that represents 'precision'",
  "An object that's been measured",
  "Something that looks like it's exact",
  "A surface with interesting alignment",
  "Something that represents 'randomness'",
  "An object that's been scattered",
  "Something that looks like it's been thrown",
  "A pattern made by chance",
  "Something that represents 'order'",
  "An object that's been organized",
  "Something that looks like it's been arranged",
  "A surface with interesting grid patterns",
  "Something that represents 'symmetry'",
  "An object that's been mirrored",
  "Something that looks the same on both sides",
  "A pattern made by repetition",
  "Something that represents 'asymmetry'",
  "An object that's been offset",
  "Something that looks intentionally unbalanced",
  "A surface with interesting irregular patterns",
  "Something that represents 'contrast'",
  "An object that's been juxtaposed",
  "Something that looks like it's opposing something else",
  "A pattern made by alternating",
  "Something that represents 'similarity'",
  "An object that's been matched",
  "Something that looks like it belongs with something",
  "A surface with interesting gradients",
  "Something that represents 'transition'",
  "An object that's been shifting",
  "Something that looks like it's in between states",
  "A pattern made by fading",
  "Something that represents 'clarity'",
  "An object that's been sharpened",
  "Something that looks like it's crystal clear",
  "A surface with interesting transparency",
  "Something that represents 'obscurity'",
  "An object that's been blurred",
  "Something that looks like it's hard to see",
  "A pattern made by fog or mist",
  "Something that represents 'focus'",
  "An object that's been centered",
  "Something that looks like the most important thing",
  "A surface with interesting depth of field",
  "Something that represents 'background'",
  "An object that's been in the distance",
  "Something that looks like it's supporting something else",
  "A pattern made by layers",
  "Something that represents 'foreground'",
  "An object that's been close up",
  "Something that looks like it's demanding attention",
  "A surface with interesting texture up close",
  "Something that represents 'perspective'",
  "An object that's been viewed from a new angle",
  "Something that looks different than expected",
  "A pattern made by viewpoint",
  "Something that represents 'scale'",
  "An object that's been shown in relation to something",
  "Something that looks bigger or smaller than it is",
  "A pattern made by proportion",
  "Something that represents 'timelessness'",
  "An object that's been unchanged",
  "Something that looks like it could be from any era",
  "A surface with interesting agelessness",
  "Something that represents 'a moment'",
  "An object that's been captured now",
  "Something that looks like it's happening right now",
  "A pattern made by the present",
  "Something that represents 'yesterday'",
  "An object that's been from the past",
  "Something that looks like it has history",
  "A pattern made by time passing",
  "Something that represents 'tomorrow'",
  "An object that's been looking forward",
  "Something that looks like it's waiting for the future",
  "A pattern made by anticipation",
  "Something that represents 'now'",
  "An object that's been in this exact moment",
  "Something that looks like it exists only right now",
  "A pattern made by the present instant",
  "Something that represents 'permanence'",
  "An object that's been lasting",
  "Something that looks like it will be here forever",
  "A surface with interesting durability",
  "Something that represents 'transience'",
  "An object that's been temporary",
  "Something that looks like it won't last",
  "A pattern made by impermanence",
  "Something that represents 'infinity'",
  "An object that's been endless",
  "Something that looks like it goes on forever",
  "A pattern made by continuation",
  "Something that represents 'a single point'",
  "An object that's been isolated",
  "Something that looks like it's the only one",
  "A pattern made by singularity",
  "Something that looks like a puzzle piece",
  "An object that's been waiting patiently",
  "Something that represents 'anticipation'",
  "A surface with interesting cracks",
  "Something that looks like it's telling a secret",
  "An object that's been perfectly placed",
  "Something that represents 'serendipity'",
  "A pattern made by chance encounters",
  "Something that looks like it belongs nowhere",
  "An object that's been left as a gift",
  "Something that represents 'gratitude'",
  "A surface with interesting history",
  "Something that looks like it has a future",
  "An object that's been found by accident",
];